Minor adjustments
git-svn-id: svn+ssh://spartan.csl.sri.com/svn/public/pvs/trunk@4939 ab98feae-9515-0410-836f-c1e8bd48b6aa

diff --git a/pvs.in b/pvs.in
--- a/pvs.in
+++ b/pvs.in
@@ -225,7 +225,12 @@ esac
 
 binpath=$PVSPATH/bin/$PVSARCH-$opsys${majvers}
 
-if [ ! "$PVSLISP" ]
+if [ -n "$PVSLISP" -a "$PVSLISP" != "allegro" -a "$PVSLISP" != "cmulisp" ]
+  then echo "ERROR: PVSLISP must be unset, or set to 'allegro' or 'cmulisp'"
+       exit 1
+fi
+
+if [ -z "$PVSLISP" ]
    then if   [ -x $binpath/devel/pvs-allegro ]
         then PVSLISP=allegro
         elif [ -x $binpath/runtime/pvs-allegro ]
@@ -237,6 +242,7 @@ if [ ! "$PVSLISP" ]
         else echo "No executable available in $binpath"
              exit 1
         fi
+  else echo "PVSLISP is set to $PVSLISP, so it will be used"
 fi
 PVSIMAGE=pvs-$PVSLISP
 
@@ -277,9 +283,9 @@ export PVSPATCHLEVEL PVSMINUSQ PVSFORCEDP PVSDEFAULTDP
 export PVSNONINTERACTIVE PVSINEMACS
 
 # Warn about for PVS_LIBRARY_PATH conflicts
-if [ "$PVS_LIBRARY_PATH" ]
+if [ -n "$PVS_LIBRARY_PATH" ]
  then
-  plibs=`for plib in ~/pvs4.0/lib/*; do if [ -d $plib -a -e $plib/.pvscontext ]; then basename $plib; fi; done`
+  plibs=`for plib in ${PVSPATH}/lib/*; do if [ -d $plib -a -f $plib/.pvscontext ]; then basename $plib; fi; done`
   for path in `echo $PVS_LIBRARY_PATH | tr ':' ' '`
    do for plib in $plibs
        do if [ -d $path/$plib ]
@@ -293,9 +299,13 @@ fi
 
 # Warn if yices is not in the path
 # Note the $SHELL call - without it, aliases (at least for tcsh) won't be found
-if [ ! `$SHELL -c "yices --version" 2> /dev/null` ]
- then echo "Warning: yices not in your PATH - the yices prover command will not work"
-      echo "Download it from http://yices.csl.sri.com and add to your PATH"
+yicesv=`$SHELL -c "yices --version" 2> /dev/null`
+if [ -z "yicesv" ]
+ then echo "Warning: yices not in your PATH - the new yices prover command"
+      echo "  will not work."
+      echo "It is not needed to run PVS, but if you want to try it out,"
+      echo "  Download it from http://yices.csl.sri.com, install it,"
+      echo "  add to your PATH, and restart PVS."
 fi
 
 pvsemacsinit="-load $PVSPATH/emacs/go-pvs.el $loadafter"
